### ISSUE TITLE
[Request] ARM64 image

### ISSUE THREAD

**Issue by Roki100** [TeamPiped/sponsorblock-mirror#8]
Any possibility to get `arm64` image built in `1337kavin/sponsorblock-mirror`?
Seems like it's already built with buildx so adding arm64 shouldnt be too difficult

**Comment by FireMasterK** [comment]
Closing this with https://github.com/TeamPiped/sponsorblock-mirror/commit/3debf1ba7ed8a7e4f27be204ac52b0f139ca54cd, wait for the build to complete.
